export default function Head() {
  return (
    <>
      <title>Linear Landing Page</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, height=device-height, initial-scale=1"
      />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
